@echo off
setlocal enabledelayedexpansion

rem Locate Visual Studio via vswhere (ships with VS Installer)
set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" set "VSWHERE=%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" (
  echo ERROR: vswhere.exe not found. Please install Visual Studio.
  exit /b 1
)

for /f "usebackq tokens=*" %%i in (`"%VSWHERE%" -latest -prerelease -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VSINSTALL=%%i"
if not defined VSINSTALL (
  echo ERROR: No Visual Studio with VC++ tools found.
  exit /b 1
)

call "%VSINSTALL%\VC\Auxiliary\Build\vcvars64.bat"

set "BUILD_DIR=build"
set "ASAN=0"

if /i "%~1"=="--asan" (
    set "BUILD_DIR=build-asan"
    set "ASAN=1"
)
if /i "%~1"=="--help" (
    echo Usage: build.bat [--asan]
    echo   ^(no args^)  Normal build, output to build\
    echo   --asan     MSVC AddressSanitizer build, output to build-asan\
    exit /b 0
)

rem Switch to script directory (so build/ is created next to build.bat)
cd /d "%~dp0"

if not exist "%BUILD_DIR%" mkdir "%BUILD_DIR%"
cd "%BUILD_DIR%"

set "CMAKE_FLAGS=-G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DVVDEC_LIBRARY_ONLY=OFF -DVVDEC_ENABLE_INTERNALS=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="/wd4819" -DCMAKE_C_FLAGS="/wd4819""

if "%ASAN%"=="1" (
    rem MSVC ASan requires debug info (/Zi) to avoid C5072 warning, which is
    rem promoted to error by VVDEC_ENABLE_WERROR. We add /Zi and disable WERROR.
    echo [ASan] /fsanitize:address + /Zi enabled, building to %BUILD_DIR%\
    set "CMAKE_FLAGS=%CMAKE_FLAGS% -DVVDEC_USE_ADDRESS_SANITIZER=ON -DVVDEC_ENABLE_WERROR=OFF -DCMAKE_CXX_FLAGS="/wd4819 /Zi" -DCMAKE_C_FLAGS="/wd4819 /Zi" -DCMAKE_EXE_LINKER_FLAGS="/DEBUG" -DCMAKE_SHARED_LINKER_FLAGS="/DEBUG""
)

if not exist build.ninja cmake %CMAKE_FLAGS% ..
if errorlevel 1 (
    echo ERROR: CMake configuration failed.
    pause
    exit /b 1
)

rem Build the shared library and the CLI app (Ninja parallelizes automatically)
cmake --build . --target vvdec vvdecapp
if errorlevel 1 (
    echo ERROR: Build failed.
    pause
    exit /b 1
)

rem YUView expects vvdecLib.dll, but CMake target name is vvdec.
rem vvdec outputs to bin\release-shared\vvdec.dll
for /r "..\bin" %%F in (vvdec.dll) do (
    copy /y "%%F" vvdecLib.dll >nul
    echo Copied: %%F -^> vvdecLib.dll
)

if "%ASAN%"=="1" (
    rem Deploy the MSVC ASan dynamic runtime DLL next to vvdecapp.exe so it can
    rem run without the host process being ASan-instrumented.
    set "ASAN_DLL_SRC=%VCToolsInstallDir%bin\Hostx64\x64\clang_rt.asan_dynamic-x86_64.dll"
    if exist "!ASAN_DLL_SRC!" (
        copy /y "!ASAN_DLL_SRC!" "..\bin\release-shared\clang_rt.asan_dynamic-x86_64.dll" >nul
        echo [ASan] Deployed clang_rt.asan_dynamic-x86_64.dll -^> ..\bin\release-shared\
    ) else (
        echo [ASan] WARNING: !ASAN_DLL_SRC! not found, copy it manually next to vvdecapp.exe
    )

    rem Generate run-asan.bat next to vvdecapp.exe. MSVC ASan writes to the OS
    rem stderr handle; redirect 2^>^&1 to capture it to asan.log.
    rem Pass through any extra args (after --asan) to vvdecapp, e.g. -b <file>.
    set "ASAN_ARGS=%*"
    rem strip leading "--asan " if present
    set "ASAN_ARGS=!ASAN_ARGS:--asan =!"
    set "ASAN_ARGS=!ASAN_ARGS:--asan=!"
    > "..\bin\release-shared\run-asan.bat" echo @echo off
    >>"..\bin\release-shared\run-asan.bat" echo rem Auto-generated by build.bat --asan. Captures ASan report to asan.log.
    >>"..\bin\release-shared\run-asan.bat" echo rem MSVC ASan writes to OS stderr handle; redirect 2^>^&1 here to capture it.
    >>"..\bin\release-shared\run-asan.bat" echo rem Usage: run-asan.bat [vvdecapp args, e.g. -b bitstream.265]
    >>"..\bin\release-shared\run-asan.bat" echo cd /d "%%~dp0"
    >>"..\bin\release-shared\run-asan.bat" echo echo [run-asan] launching vvdecapp.exe, report -^> asan.log
    >>"..\bin\release-shared\run-asan.bat" echo vvdecapp.exe !ASAN_ARGS! %%* -^> asan.log 2^>^&1
    >>"..\bin\release-shared\run-asan.bat" echo echo [run-asan] exit code %%ERRORLEVEL%%
    >>"..\bin\release-shared\run-asan.bat" echo echo Report: %%~dp0asan.log
    >>"..\bin\release-shared\run-asan.bat" echo pause
    echo [ASan] Generated run-asan.bat -^> ..\bin\release-shared\
)

echo.
echo === vvdec build done ===
echo Output: %BUILD_DIR%\vvdecLib.dll
if "%ASAN%"=="1" (
    echo Test:   ..\bin\release-shared\run-asan.bat ^(double-click to run^)
    echo Report: ..\bin\release-shared\asan.log
)
pause
